const fs = require('fs');
const path = require('path');

const symbolsData = [
  // --- عرضه‌های اولیه و نمادهای پرطرفدار اخیر ---
  { symbol: "فزر", name: "پویا زرکان آق دره", isin: "IRO1FAZR0001", group: "استخراج کانه‌های فلزی", market: "فرابورس", isIpo: true },
  { symbol: "پی‌پاد", name: "پرداخت الکترونیک پاسارگاد", isin: "IRO1PPAD0001", group: "رایانه و فعالیت‌های وابسته", market: "بورس", isIpo: true },
  { symbol: "وسپهر", name: "سرمایه‌گذاری مالی سپهر صادرات", isin: "IRO1SPHR0001", group: "سرمایه‌گذاری‌ها", market: "فرابورس", isIpo: true },
  { symbol: "وکغدیر", name: "توسعه صنایع و معادن غدیر", isin: "IRO1KGHD0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: true },
  { symbol: "ناما", name: "ماموت دیزل", isin: "IRO1NAMA0001", group: "خودرو و قطعات", market: "فرابورس", isIpo: true },
  { symbol: "اردستان", name: "سیمان اردستان", isin: "IRO1ARDS0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: true },
  { symbol: "فروژ", name: "صنایع فروآلیاژ ایران", isin: "IRO1FROZ0001", group: "فلزات اساسی", market: "فرابورس", isIpo: true },
  { symbol: "تپسی", name: "پیشگامان فن‌آوری و دانش آرامیس", isin: "IRO1TPSI0001", group: "رایانه و فناوری اطلاعات", market: "فرابورس", isIpo: true },
  { symbol: "کروم", name: "توسعه معادن کرومیت خاورمیانه", isin: "IRO1KROM0001", group: "استخراج کانه‌های فلزی", market: "فرابورس", isIpo: true },
  { symbol: "کتوسعه", name: "توسعه صنایع و معادن کوثر", isin: "IRO1KTOS0001", group: "استخراج کانه‌های فلزی", market: "فرابورس", isIpo: true },
  { symbol: "کایزد", name: "فولاد الماس یزد", isin: "IRO1KAYZ0001", group: "فلزات اساسی", market: "فرابورس", isIpo: true },
  { symbol: "زفجر", name: "کشاورزی و دامپروری فجر اصفهان", isin: "IRO1ZFJR0001", group: "زراعت و دامپروری", market: "فرابورس", isIpo: true },
  { symbol: "سپید", name: "سپید ماکیان", isin: "IRO1SPID0001", group: "زراعت و دامپروری", market: "بورس", isIpo: true },
  { symbol: "شستا", name: "سرمایه‌گذاری تامین اجتماعی", isin: "IRO1SSST0001", group: "چندرشته‌ای صنعتی", market: "بورس", isIpo: false },

  // --- فلزات اساسی ---
  { symbol: "فولاد", name: "فولاد مبارکه اصفهان", isin: "IRO1FOLD0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فملی", name: "ملی صنایع مس ایران", isin: "IRO1MSMI0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "ذوب", name: "ذوب آهن اصفهان", isin: "IRO1ZOBN0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "فخوز", name: "فولاد خوزستان", isin: "IRO1FKHZ0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "کاوه", name: "فولاد کاوه جنوب کیش", isin: "IRO1KAVE0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فخاس", name: "فولاد خراسان", isin: "IRO1FKHS0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فاسمین", name: "کالسیمین", isin: "IRO1FASM0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فباهنر", name: "مس شهید باهنر", isin: "IRO1FBAH0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فسرب", name: "ملی سرب و روی ایران", isin: "IRO1FSRB0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فرآور", name: "فرآوری مواد معدنی ایران", isin: "IRO1FRAV0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فنوال", name: "نورد آلومینیوم", isin: "IRO1FNVL0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فپنتا", name: "سپنتا", isin: "IRO1FPNT0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فجهان", name: "مجتمع جهان فولاد سیرجان", isin: "IRO1FJHN0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "فسبزوار", name: "پارس فولاد سبزوار", isin: "IRO1FSBZ0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فسفها", name: "فولاد سپید فراب کویر", isin: "IRO1FSFH0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فمراد", name: "آلومراد", isin: "IRO1FMRD0001", group: "فلزات اساسی", market: "بورس", isIpo: false },
  { symbol: "فتوسا", name: "تولید و توسعه سرب و روی ایرانیان", isin: "IRO1FTOS0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "فزرین", name: "زرین معدن آسیا", isin: "IRO1FZRN0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "فغدیر", name: "آهن و فولاد غدیر ایرانیان", isin: "IRO1FGHD0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "ارفع", name: "آهن و فولاد ارفع", isin: "IRO1ARFA0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },
  { symbol: "هرمز", name: "فولاد هرمزگان جنوب", isin: "IRO1HRMZ0001", group: "فلزات اساسی", market: "فرابورس", isIpo: false },

  // --- خودرو و ساخت قطعات ---
  { symbol: "خودرو", name: "ایران خودرو", isin: "IRO1IKCO0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خساپا", name: "سایپا", isin: "IRO1SIPA0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خگستر", name: "گسترش سرمایه‌گذاری ایران خودرو", isin: "IRO1KGST0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خبهمن", name: "گروه بهمن", isin: "IRO1BHMN0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خزامیا", name: "زامیاد", isin: "IRO1ZAMD0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خپارس", name: "پارس خودرو", isin: "IRO1PARS0001", group: "خودرو و قطعات", market: "پایه", isIpo: false },
  { symbol: "خاور", name: "ایران خودرو دیزل", isin: "IRO1KHVR0001", group: "خودرو و قطعات", market: "پایه", isIpo: false },
  { symbol: "خمحرکه", name: "نیرو محرکه", isin: "IRO1KMHR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خکمک", name: "کمک فنر ایندامین", isin: "IRO1KMKM0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خریخت", name: "ریخته‌گری تراکتورسازی ایران", isin: "IRO1RIKH0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "ختور", name: "رادیاتور ایران", isin: "IRO1KTOR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "ختراک", name: "ریخته‌گری ایران خودرو", isin: "IRO1KTRK0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خپویش", name: "سازه‌پویش", isin: "IRO1KPYS0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خرینگ", name: "رینگ‌سازی مشهد", isin: "IRO1KRNG0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خکار", name: "ایران کاربراتور", isin: "IRO1KKAR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خاذین", name: "آذین خودرو", isin: "IRO1KAZN0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خاهن", name: "آهنگری تراکتورسازی ایران", isin: "IRO1KAHN0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خشرق", name: "الکتریک خودرو شرق", isin: "IRO1KSHR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خنصیر", name: "مهندسی نصیر ماشین", isin: "IRO1KNSR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خموتور", name: "موتورسازان تراکتورسازی", isin: "IRO1KMTR0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خوساز", name: "محور سازان ایران خودرو", isin: "IRO1KOSZ0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "ختوقا", name: "قطعات اتومبیل ایران", isin: "IRO1KTOQ0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },
  { symbol: "خلنت", name: "لنت ترمز ایران", isin: "IRO1KLNT0001", group: "خودرو و قطعات", market: "بورس", isIpo: false },

  // --- محصولات شیمیایی و پتروشیمی ---
  { symbol: "فارس", name: "صنایع پتروشیمی خلیج فارس", isin: "IRO1FARS0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "نوری", name: "پتروشیمی نوری", isin: "IRO1PNOR0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شپدیس", name: "پتروشیمی پردیس", isin: "IRO1PDIS0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "پارسان", name: "گسترش نفت و گاز پارسیان", isin: "IRO1PRSN0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "زاگرس", name: "پتروشیمی زاگرس", isin: "IRO1ZGRS0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "جم", name: "پتروشیمی جم", isin: "IRO1PJAM0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شاراک", name: "پتروشیمی شازند", isin: "IRO1ARAK0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "کرماشا", name: "صنایع پتروشیمی کرمانشاه", isin: "IRO1KMSH0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "پارس", name: "پتروشیمی پارس", isin: "IRO1PARS0002", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "آریا", name: "پلیمر آریا ساسول", isin: "IRO1ARYA0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شگویا", name: "پتروشیمی شهید تندگویان", isin: "IRO1SGYA0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شیراز", name: "پتروشیمی شیراز", isin: "IRO1SHRZ0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شفن", name: "پتروشیمی فن آوران", isin: "IRO1SHFN0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "بوعلی", name: "پتروشیمی بوعلی سینا", isin: "IRO1BOAL0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شبصیر", name: "تولیدی پلاستوفوم قائد بصیر", isin: "IRO1SBCR0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شجم", name: "پتروشیمی جم پیلن", isin: "IRO1SHJM0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شغدیر", name: "پتروشیمی غدیر", isin: "IRO1SGHD0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شکربن", name: "کربن ایران", isin: "IRO1SKRB0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "شصفها", name: "پتروشیمی اصفهان", isin: "IRO1PSFH0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "کلر", name: "کلرپارس", isin: "IRO1CLOR0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شپترو", name: "پتروشیمی آبادان", isin: "IRO1SPTR0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "پاکشو", name: "گروه صنعتی پاکشو", isin: "IRO1PKSH0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "قرن", name: "پدیده شیمی قرن", isin: "IRO1QARN0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },
  { symbol: "ساینا", name: "صنایع بهداشتی ساینا", isin: "IRO1SAYN0001", group: "محصولات شیمیایی", market: "فرابورس", isIpo: false },
  { symbol: "شوینده", name: "مدیریت صنعت شوینده", isin: "IRO1SHND0001", group: "محصولات شیمیایی", market: "بورس", isIpo: false },

  // --- فرآورده‌های نفتی و پالایشی ---
  { symbol: "شتران", name: "پالایش نفت تهران", isin: "IRO1SHTR0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شپنا", name: "پالایش نفت اصفهان", isin: "IRO1SHPN0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شبندر", name: "پالایش نفت بندرعباس", isin: "IRO1BNDR0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شاوان", name: "پالایش نفت لاوان", isin: "IRO1LAVN0001", group: "فرآورده‌های نفتی", market: "فرابورس", isIpo: false },
  { symbol: "شراز", name: "پالایش نفت شیراز", isin: "IRO1SHRZ0002", group: "فرآورده‌های نفتی", market: "فرابورس", isIpo: false },
  { symbol: "شبریز", name: "پالایش نفت تبریز", isin: "IRO1SBRZ0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "ونفت", name: "سرمایه‌گذاری صنعت نفت", isin: "IRO1VNFT0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شنفت", name: "نفت پارس", isin: "IRO1SNFT0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شرانل", name: "نفت ایرانول", isin: "IRO1IRNL0001", group: "فرآورده‌های نفتی", market: "فرابورس", isIpo: false },
  { symbol: "شسپا", name: "نفت سپاهان", isin: "IRO1SSPA0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },
  { symbol: "شبهرن", name: "نفت بهران", isin: "IRO1SBHR0001", group: "فرآورده‌های نفتی", market: "بورس", isIpo: false },

  // --- بانک‌ها و موسسات اعتباری ---
  { symbol: "وبملت", name: "بانک ملت", isin: "IRO1BMLT0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وتجارت", name: "بانک تجارت", isin: "IRO1BTEJ0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وبصادر", name: "بانک صادرات ایران", isin: "IRO1BSDR0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "ونوین", name: "بانک اقتصاد نوین", isin: "IRO1BENO0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وپاسار", name: "بانک پاسارگاد", isin: "IRO1BPAS0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وخاور", name: "بانک خاورمیانه", isin: "IRO1BKHR0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "سامان", name: "بانک سامان", isin: "IRO1BSMN0001", group: "بانک‌ها و موسسات اعتباری", market: "فرابورس", isIpo: false },
  { symbol: "وکار", name: "بانک کارآفرین", isin: "IRO1BKAR0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وپارس", name: "بانک پارسیان", isin: "IRO1BPRS0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وسینا", name: "بانک سینا", isin: "IRO1BSIN0001", group: "بانک‌ها و موسسات اعتباری", market: "بورس", isIpo: false },
  { symbol: "وگردش", name: "بانک گردشگری", isin: "IRO1BGRD0001", group: "بانک‌ها و موسسات اعتباری", market: "پایه", isIpo: false },
  { symbol: "رسالت", name: "بانک قرض‌الحسنه رسالت", isin: "IRO1RSLT0001", group: "بانک‌ها و موسسات اعتباری", market: "پایه", isIpo: false },
  { symbol: "دی", name: "بانک دی", isin: "IRO1BDAY0001", group: "بانک‌ها و موسسات اعتباری", market: "پایه", isIpo: false },
  { symbol: "شهر", name: "بانک شهر", isin: "IRO1BSHR0001", group: "بانک‌ها و موسسات اعتباری", market: "پایه", isIpo: false },

  // --- سرمایه‌گذاری‌ها و چندرشته‌ای ---
  { symbol: "وغدیر", name: "سرمایه‌گذاری غدیر", isin: "IRO1GDIR0001", group: "چندرشته‌ای صنعتی", market: "بورس", isIpo: false },
  { symbol: "وامید", name: "مدیریت سرمایه‌گذاری امید", isin: "IRO1OMID0001", group: "چندرشته‌ای صنعتی", market: "بورس", isIpo: false },
  { symbol: "وبانک", name: "سرمایه‌گذاری گروه توسعه ملی", isin: "IRO1BANK0001", group: "چندرشته‌ای صنعتی", market: "بورس", isIpo: false },
  { symbol: "وصندوق", name: "سرمایه‌گذاری صندوق بازنشستگی", isin: "IRO1SNDQ0001", group: "چندرشته‌ای صنعتی", market: "بورس", isIpo: false },
  { symbol: "ومعادن", name: "توسعه معادن و فلزات", isin: "IRO1MADN0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "وسپه", name: "سرمایه‌گذاری سپه", isin: "IRO1SPAH0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "ونیکی", name: "سرمایه‌گذاری ملی ایران", isin: "IRO1NIKI0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "وتوسم", name: "سرمایه‌گذاری توسعه ملی", isin: "IRO1TOSM0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "وخارزم", name: "سرمایه‌گذاری خوارزمی", isin: "IRO1KHRZ0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "صبا", name: "گروه مالی صبا تامین", isin: "IRO1SABA0001", group: "سرمایه‌گذاری‌ها", market: "فرابورس", isIpo: false },
  { symbol: "تاصیکو", name: "سرمایه‌گذاری صدر تامین", isin: "IRO1TASI0001", group: "استخراج کانه‌های فلزی", market: "بورس", isIpo: false },
  { symbol: "پویا", name: "سرمایه‌گذاری پویا", isin: "IRO1POYA0001", group: "سرمایه‌گذاری‌ها", market: "فرابورس", isIpo: false },
  { symbol: "سرچشمه", name: "سرمایه‌گذاری مس سرچشمه", isin: "IRO1SRCH0001", group: "سرمایه‌گذاری‌ها", market: "بورس", isIpo: false },
  { symbol: "گوهران", name: "سرمایه‌گذاری گوهران امید", isin: "IRO1GOHR0001", group: "سرمایه‌گذاری‌ها", market: "فرابورس", isIpo: false },

  // --- صندوق‌های طلا و اهرمی (ETFs) ---
  { symbol: "طلا", name: "صندوق طلای لوتوس", isin: "IRO1TALA0001", group: "صندوق سرمایه‌گذاری طلا", market: "بورس", isIpo: false },
  { symbol: "عیار", name: "صندوق طلای عیار مفید", isin: "IRO1AYAR0001", group: "صندوق سرمایه‌گذاری طلا", market: "فرابورس", isIpo: false },
  { symbol: "کهربا", name: "صندوق طلای کهربا", isin: "IRO1KHRB0001", group: "صندوق سرمایه‌گذاری طلا", market: "فرابورس", isIpo: false },
  { symbol: "زر", name: "صندوق طلای زرفام", isin: "IRO1ZARR0001", group: "صندوق سرمایه‌گذاری طلا", market: "بورس", isIpo: false },
  { symbol: "گوهر", name: "صندوق طلای گوهر", isin: "IRO1GOHR0002", group: "صندوق سرمایه‌گذاری طلا", market: "فرابورس", isIpo: false },
  { symbol: "ناب", name: "صندوق طلای صبا ناب", isin: "IRO1NAAB0001", group: "صندوق سرمایه‌گذاری طلا", market: "فرابورس", isIpo: false },
  { symbol: "اهرم", name: "صندوق اهرمی کاریزما", isin: "IRO1AHRM0001", group: "صندوق اهرمی", market: "بورس", isIpo: false },
  { symbol: "موج", name: "صندوق اهرمی موج فیروزه", isin: "IRO1MOOJ0001", group: "صندوق اهرمی", market: "بورس", isIpo: false },
  { symbol: "شتاب", name: "صندوق اهرمی شتاب آگاه", isin: "IRO1SHTB0001", group: "صندوق اهرمی", market: "فرابورس", isIpo: false },
  { symbol: "جهش", name: "صندوق اهرمی جهش فارابی", isin: "IRO1JHSH0001", group: "صندوق اهرمی", market: "فرابورس", isIpo: false },
  { symbol: "توان", name: "صندوق اهرمی توان مفید", isin: "IRO1TVAN0001", group: "صندوق اهرمی", market: "فرابورس", isIpo: false },
  { symbol: "نارنج", name: "صندوق اهرمی نارنج ترنج", isin: "IRO1NRNJ0001", group: "صندوق اهرمی", market: "فرابورس", isIpo: false },
  { symbol: "دارایکم", name: "واسطه‌گری مالی یکم", isin: "IRO1DARA0001", group: "صندوق سرمایه‌گذاری دولتی", market: "بورس", isIpo: false },
  { symbol: "پالایش", name: "پالایشی یکم", isin: "IRO1PALY0001", group: "صندوق سرمایه‌گذاری دولتی", market: "بورس", isIpo: false },
  { symbol: "آگاس", name: "صندوق هستی بخش آگاه", isin: "IRO1AGAS0001", group: "صندوق سرمایه‌گذاری سهامی", market: "بورس", isIpo: false },
  { symbol: "سرو", name: "صندوق سرو صادرات", isin: "IRO1SRVO0001", group: "صندوق سرمایه‌گذاری سهامی", market: "فرابورس", isIpo: false },

  // --- استخراج کانه‌های فلزی ---
  { symbol: "کچاد", name: "معدنی و صنعتی چادرملو", isin: "IRO1CHAD0001", group: "استخراج کانه‌های فلزی", market: "بورس", isIpo: false },
  { symbol: "کگل", name: "معدنی و صنعتی گل گهر", isin: "IRO1GOLG0001", group: "استخراج کانه‌های فلزی", market: "بورس", isIpo: false },
  { symbol: "کاما", name: "باما", isin: "IRO1BAMA0001", group: "استخراج کانه‌های فلزی", market: "بورس", isIpo: false },
  { symbol: "کمنگنز", name: "معادن منگنز ایران", isin: "IRO1MNGN0001", group: "استخراج کانه‌های فلزی", market: "بورس", isIpo: false },
  { symbol: "کزغال", name: "زغال سنگ پروده طبس", isin: "IRO1PZGH0001", group: "استخراج زغال سنگ", market: "فرابورس", isIpo: false },
  { symbol: "کطبس", name: "توسعه بازرگانی آهن و فولاد لوتوس", isin: "IRO1TBAS0001", group: "استخراج زغال سنگ", market: "بورس", isIpo: false },
  { symbol: "کشرق", name: "صنعتی و معدنی شمال شرق شاهرود", isin: "IRO1SHRQ0001", group: "استخراج زغال سنگ", market: "فرابورس", isIpo: false },

  // --- سیمان، آهک و گچ ---
  { symbol: "سیتا", name: "سرمایه‌گذاری سیمان تامین", isin: "IRO1SITA0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "ستران", name: "سیمان تهران", isin: "IRO1STRN0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "ساوه", name: "سیمان ساوه", isin: "IRO1SAVE0001", group: "سیمان، آهک و گچ", market: "فرابورس", isIpo: false },
  { symbol: "سخوز", name: "سیمان خوزستان", isin: "IRO1SKHZ0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سشرق", name: "سیمان شرق", isin: "IRO1SSHR0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سدور", name: "سیمان دورود", isin: "IRO1SDOR0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سفارس", name: "سیمان فارس و خوزستان", isin: "IRO1SFAR0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سپاها", name: "سیمان سپاهان", isin: "IRO1SPHN0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سصوفی", name: "سیمان صوفیان", isin: "IRO1SSOF0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "ساروم", name: "سیمان ارومیه", isin: "IRO1SROM0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },
  { symbol: "سابیک", name: "سیمان آبیک", isin: "IRO1SABK0001", group: "سیمان، آهک و گچ", market: "بورس", isIpo: false },

  // --- مواد و محصولات دارویی ---
  { symbol: "برکت", name: "گروه دارویی برکت", isin: "IRO1BRKT0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "تیپیکو", name: "سرمایه‌گذاری دارویی تامین", isin: "IRO1TPCO0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "والبر", name: "سرمایه‌گذاری البرز", isin: "IRO1ALBR0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دسبحان", name: "سبحان دارو", isin: "IRO1DSBH0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دابور", name: "داروسازی ابوریحان", isin: "IRO1DABR0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دپارس", name: "پارس دارو", isin: "IRO1DPAR0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "درازک", name: "لابراتوارهای رازک", isin: "IRO1DRAZ0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دلقما", name: "دارویی لقمان", isin: "IRO1DLQM0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دسینا", name: "داروسازی سینا", isin: "IRO1DSIN0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دکپسول", name: "تولید ژلاتین کپسول ایران", isin: "IRO1DKPS0001", group: "مواد و محصولات دارویی", market: "فرابورس", isIpo: false },
  { symbol: "دتماد", name: "تولید مواد اولیه داروپخش", isin: "IRO1DTMD0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "دفارا", name: "داروسازی فارابی", isin: "IRO1DFAR0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },
  { symbol: "پخش", name: "پخش البرز", isin: "IRO1PAKH0001", group: "مواد و محصولات دارویی", market: "فرابورس", isIpo: false },
  { symbol: "هجرت", name: "پخش هجرت", isin: "IRO1HJRT0001", group: "مواد و محصولات دارویی", market: "بورس", isIpo: false },

  // --- محصولات غذایی و آشامیدنی ---
  { symbol: "غکورش", name: "صنعت غذایی کورش", isin: "IRO1GKOR0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غزر", name: "زر ماکارون", isin: "IRO1GZAR0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غنوش", name: "نوش مازندران", isin: "IRO1GNOS0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غمارگ", name: "مارگارین", isin: "IRO1GMAR0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غدیس", name: "پاکدیس", isin: "IRO1GDIS0001", group: "محصولات غذایی", market: "فرابورس", isIpo: false },
  { symbol: "غبشهر", name: "صنعتی بهشهر", isin: "IRO1GBSH0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غصینو", name: "صنعتی مینو", isin: "IRO1GSIN0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غپاک", name: "لبنیات پاک", isin: "IRO1GPAK0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غبهنوش", name: "بهنوش ایران", isin: "IRO1GBHN0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غپینو", name: "پارس مینو", isin: "IRO1GPIN0001", group: "محصولات غذایی", market: "بورس", isIpo: false },
  { symbol: "غشهداب", name: "کشت و صنعت شهداب ناب خراسان", isin: "IRO1GSHD0001", group: "محصولات غذایی", market: "فرابورس", isIpo: false },
  { symbol: "غگیلا", name: "پگاه گیلان", isin: "IRO1GGIL0001", group: "محصولات غذایی", market: "فرابورس", isIpo: false },

  // --- انبوه سازی و املاک ---
  { symbol: "کرمان", name: "سرمایه‌گذاری توسعه و عمران کرمان", isin: "IRO1KRMN0001", group: "املاک و مستغلات", market: "فرابورس", isIpo: false },
  { symbol: "ثشاهد", name: "سرمایه‌گذاری شاهد", isin: "IRO1SHHD0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثفارس", name: "عمران و مسکن سازان فارس", isin: "IRO1TFRS0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثامان", name: "سامان گستر اصفهان", isin: "IRO1SMAN0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثنوسا", name: "نوسازی و ساختمان تهران", isin: "IRO1TNSA0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثتران", name: "سرمایه‌گذاری مسکن تهران", isin: "IRO1TTRN0001", group: "املاک و مستغلات", market: "فرابورس", isIpo: false },
  { symbol: "ثمسکن", name: "سرمایه‌گذاری مسکن", isin: "IRO1TMSK0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثپردیس", name: "سرمایه‌گذاری مسکن پردیس", isin: "IRO1TPRD0001", group: "املاک و مستغلات", market: "فرابورس", isIpo: false },
  { symbol: "ثبهساز", name: "بهساز کاشانه تهران", isin: "IRO1TBHZ0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },
  { symbol: "ثامید", name: "توسعه و عمران امید", isin: "IRO1TOMD0001", group: "املاک و مستغلات", market: "بورس", isIpo: false },

  // --- فناوری اطلاعات و رایانه ---
  { symbol: "آپ", name: "آسان پرداخت پرشین", isin: "IRO1ASAN0001", group: "رایانه و فناوری اطلاعات", market: "بورس", isIpo: false },
  { symbol: "رانفور", name: "خدمات انفورماتیک", isin: "IRO1INFO0001", group: "رایانه و فناوری اطلاعات", market: "بورس", isIpo: false },
  { symbol: "سپیدار", name: "سپیدار سیستم آسیا", isin: "IRO1SPDR0001", group: "رایانه و فناوری اطلاعات", market: "فرابورس", isIpo: false },
  { symbol: "سیستم", name: "همکاران سیستم", isin: "IRO1SYST0001", group: "رایانه و فناوری اطلاعات", market: "بورس", isIpo: false },
  { symbol: "توسن", name: "توسعه سامانه‌های نرم‌افزاری نگین", isin: "IRO1TOSN0001", group: "رایانه و فناوری اطلاعات", market: "فرابورس", isIpo: false },
  { symbol: "پرداخت", name: "داده گستر عصر نوین (های‌وب)", isin: "IRO1HIWB0001", group: "رایانه و فناوری اطلاعات", market: "بورس", isIpo: false },
  { symbol: "افق", name: "فروشگاه‌های زنجیره‌ای افق کوروش", isin: "IRO1OFOQ0001", group: "خرده‌فروشی", market: "بورس", isIpo: false },

  // --- بیمه و بازنشستگی ---
  { symbol: "البرز", name: "بیمه البرز", isin: "IRO1ALBR0002", group: "بیمه و صندوق بازنشستگی", market: "بورس", isIpo: false },
  { symbol: "آسیا", name: "بیمه آسیا", isin: "IRO1ASIA0001", group: "بیمه و صندوق بازنشستگی", market: "بورس", isIpo: false },
  { symbol: "دانا", name: "بیمه دانا", isin: "IRO1DANA0001", group: "بیمه و صندوق بازنشستگی", market: "بورس", isIpo: false },
  { symbol: "بپاس", name: "بیمه پاسارگاد", isin: "IRO1BPAS0002", group: "بیمه و صندوق بازنشستگی", market: "فرابورس", isIpo: false },
  { symbol: "بساما", name: "بیمه سامان", isin: "IRO1BSMN0002", group: "بیمه و صندوق بازنشستگی", market: "فرابورس", isIpo: false },
  { symbol: "کوثر", name: "بیمه کوثر", isin: "IRO1KVSR0001", group: "بیمه و صندوق بازنشستگی", market: "فرابورس", isIpo: false },
  { symbol: "ما", name: "بیمه ما", isin: "IRO1BMAA0001", group: "بیمه و صندوق بازنشستگی", market: "بورس", isIpo: false },

  // --- نیروگاهی و برق ---
  { symbol: "بپیوند", name: "تولید برق پیوند گستر پارس", isin: "IRO1BPYD0001", group: "عرضه برق و گاز", market: "فرابورس", isIpo: false },
  { symbol: "بگیلان", name: "توسعه مسیر برق گیلان", isin: "IRO1BGLN0001", group: "عرضه برق و گاز", market: "فرابورس", isIpo: false },
  { symbol: "بجهرم", name: "توسعه مولد نیروگاهی جهرم", isin: "IRO1BJHR0001", group: "عرضه برق و گاز", market: "فرابورس", isIpo: false },
  { symbol: "دماوند", name: "تولید نیروی برق دماوند", isin: "IRO1DMVN0001", group: "عرضه برق و گاز", market: "فرابورس", isIpo: false },
  { symbol: "رمپنا", name: "گروه مپنا", isin: "IRO1MAPN0001", group: "خدمات فنی و مهندسی", market: "بورس", isIpo: false },
  { symbol: "بفجر", name: "فجر انرژی خلیج فارس", isin: "IRO1FAJR0001", group: "عرضه برق و گاز", market: "بورس", isIpo: false },
  { symbol: "مبین", name: "پتروشیمی مبین", isin: "IRO1MOBN0001", group: "عرضه برق و گاز", market: "بورس", isIpo: false },

  // --- حمل و نقل ---
  { symbol: "حکشتی", name: "کشتیرانی جمهوری اسلامی ایران", isin: "IRO1KSHI0001", group: "حمل و نقل و انبارداری", market: "بورس", isIpo: false },
  { symbol: "حریل", name: "ریل سیر کوثر", isin: "IRO1RILK0001", group: "حمل و نقل و انبارداری", market: "فرابورس", isIpo: false },
  { symbol: "حسینا", name: "توسعه خدمات دریایی و بندری سینا", isin: "IRO1SINA0001", group: "حمل و نقل و انبارداری", market: "فرابورس", isIpo: false },
  { symbol: "حتاید", name: "تایدواتر خاورمیانه", isin: "IRO1TIDE0001", group: "حمل و نقل و انبارداری", market: "بورس", isIpo: false },
  { symbol: "حفارس", name: "حمل و نقل بین‌المللی خلیج فارس", isin: "IRO1HFRS0001", group: "حمل و نقل و انبارداری", market: "بورس", isIpo: false }
];

const targetDir = path.resolve(__dirname, '../src/data');
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(
  path.join(targetDir, 'symbols.json'),
  JSON.stringify(symbolsData, null, 2),
  'utf8'
);

console.log(`Successfully generated symbols.json with ${symbolsData.length} symbols.`);
